// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for AboutPage documents */
interface AboutpageDocumentData {
    /**
     * title field in *AboutPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: aboutpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Slice Zone field in *AboutPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: aboutpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<AboutpageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *AboutPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: aboutpage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *AboutPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: aboutpage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *AboutPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: aboutpage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *AboutPage → Slice Zone*
 *
 */
type AboutpageDocumentDataSlicesSlice = CtaSliceSlice | ContentSliceSlice | FeaturesSliceSlice | TeamSliceSlice;
/**
 * AboutPage document from Prismic
 *
 * - **API ID**: `aboutpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<AboutpageDocumentData>,
    "aboutpage",
    Lang
>;
/** Content for BlogPage documents */
interface BlogpageDocumentData {
    /**
     * title field in *BlogPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Slice Zone field in *BlogPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<BlogpageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *BlogPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: blogpage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *BlogPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *BlogPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: blogpage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *BlogPage → Slice Zone*
 *
 */
type BlogpageDocumentDataSlicesSlice = never;
/**
 * BlogPage document from Prismic
 *
 * - **API ID**: `blogpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<BlogpageDocumentData>,
    "blogpage",
    Lang
>;
/** Content for BlogPost documents */
interface BlogpostDocumentData {
    /**
     * title field in *BlogPost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *BlogPost*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismic.RichTextField;
    /**
     * minutesToRead field in *BlogPost*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.minutestoread
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    minutestoread: prismic.NumberField;
    /**
     * image field in *BlogPost*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Slice Zone field in *BlogPost*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *BlogPost*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: blogpost.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *BlogPost*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpost.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *BlogPost*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: blogpost.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *BlogPost → Slice Zone*
 *
 */
type BlogpostDocumentDataSlicesSlice = BlogParagraphSlice | CtaSliceSlice | YoutubePlayerSlice;
/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
>;
/** Content for ContactPage documents */
interface ContactpageDocumentData {
    /**
     * title field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * pitch field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.pitch
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    pitch: prismic.KeyTextField;
    /**
     * phoneHeader field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.phoneheader
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phoneheader: prismic.KeyTextField;
    /**
     * phone field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone: prismic.KeyTextField;
    /**
     * email field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismic.KeyTextField;
    /**
     * addressHeader field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.addressheader
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    addressheader: prismic.KeyTextField;
    /**
     * address field in *ContactPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    address: prismic.RichTextField;
    /**
     * openingHours field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.openinghours
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    openinghours: prismic.KeyTextField;
    /**
     * addressGeoPoint field in *ContactPage*
     *
     * - **Field Type**: GeoPoint
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.addressgeopoint
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
     *
     */
    addressgeopoint: prismic.GeoPointField;
    /**
     * Slice Zone field in *ContactPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<ContactpageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *ContactPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: contactpage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *ContactPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: contactpage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *ContactPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: contactpage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *ContactPage → Slice Zone*
 *
 */
type ContactpageDocumentDataSlicesSlice = never;
/**
 * ContactPage document from Prismic
 *
 * - **API ID**: `contactpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<ContactpageDocumentData>,
    "contactpage",
    Lang
>;
/** Content for ContactPrompt documents */
interface ContactpromptDocumentData {
    /**
     * title field in *ContactPrompt*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactprompt.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *ContactPrompt*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactprompt.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * contactLink field in *ContactPrompt*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contactprompt.contactlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contactlink: prismic.LinkField;
    /**
     * contactButtonText field in *ContactPrompt*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contactprompt.contactbuttontext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contactbuttontext: prismic.KeyTextField;
}
/**
 * ContactPrompt document from Prismic
 *
 * - **API ID**: `contactprompt`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactpromptDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<ContactpromptDocumentData>,
    "contactprompt",
    Lang
>;
/** Content for FAQIndividualQuestion documents */
interface FaqindividualquestionDocumentData {
    /**
     * question field in *FAQIndividualQuestion*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faqindividualquestion.question
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    question: prismic.KeyTextField;
    /**
     * Slice Zone field in *FAQIndividualQuestion*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: faqindividualquestion.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<FaqindividualquestionDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *FAQIndividualQuestion*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: faqindividualquestion.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *FAQIndividualQuestion*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: faqindividualquestion.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *FAQIndividualQuestion*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: faqindividualquestion.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *FAQIndividualQuestion → Slice Zone*
 *
 */
type FaqindividualquestionDocumentDataSlicesSlice = BlogParagraphSlice | YoutubePlayerSlice | CtaSliceSlice;
/**
 * FAQIndividualQuestion document from Prismic
 *
 * - **API ID**: `faqindividualquestion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqindividualquestionDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<FaqindividualquestionDocumentData>,
    "faqindividualquestion",
    Lang
>;
/** Content for FaqPage documents */
interface FaqpageDocumentData {
    /**
     * Slice Zone field in *FaqPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: faqpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<FaqpageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *FaqPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: faqpage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *FaqPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: faqpage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *FaqPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: faqpage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *FaqPage → Slice Zone*
 *
 */
type FaqpageDocumentDataSlicesSlice = CtaSliceSlice | FaqSliceSlice;
/**
 * FaqPage document from Prismic
 *
 * - **API ID**: `faqpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FaqpageDocumentData>,
    "faqpage",
    Lang
>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * copyright field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    copyright: prismic.KeyTextField;
    /**
     * cookies field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.cookies
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cookies: prismic.KeyTextField;
    /**
     * privacyLinkText field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.privacylinktext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    privacylinktext: prismic.KeyTextField;
    /**
     * privacyLink field in *Footer*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.privacylink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    privacylink: prismic.LinkField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
>;
/** Content for GlobalNavigation documents */
interface GlobalnavigationDocumentData {
    /**
     * Logo field in *GlobalNavigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismic.ImageField<never>;
    /**
     * mainlink field in *GlobalNavigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.mainlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    mainlink: prismic.LinkField;
    /**
     * contactLink field in *GlobalNavigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.contactlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contactlink: prismic.LinkField;
    /**
     * contacttext field in *GlobalNavigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.contacttext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contacttext: prismic.KeyTextField;
    /**
     * facebookLink field in *GlobalNavigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.facebooklink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    facebooklink: prismic.LinkField;
    /**
     * whatsappLink field in *GlobalNavigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.whatsapplink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    whatsapplink: prismic.LinkField;
    /**
     * instagramLink field in *GlobalNavigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.instagramlink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    instagramlink: prismic.LinkField;
    /**
     * Slice Zone field in *GlobalNavigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: globalnavigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<GlobalnavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *GlobalNavigation → Slice Zone*
 *
 */
type GlobalnavigationDocumentDataSlicesSlice = NavigationItemSlice;
/**
 * GlobalNavigation document from Prismic
 *
 * - **API ID**: `globalnavigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalnavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalnavigationDocumentData>,
    "globalnavigation",
    Lang
>;
/** Content for HomePage documents */
interface HomepageDocumentData {
    /**
     * Title field in *HomePage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * Slice Zone field in *HomePage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *HomePage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: homepage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *HomePage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *HomePage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: homepage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *HomePage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice =
    | MainPitchSliceSlice
    | FeaturesSliceSlice
    | ClientTypesSliceSlice
    | ClientReviewsSliceSlice
    | CtaSliceSlice
    | CompanyLogosSlice
    | YoutubePlayerSlice;
/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
>;
/** Content for OfferItemPage documents */
interface OfferitempageDocumentData {
    /**
     * title field in *OfferItemPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offeritempage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * offerTarget field in *OfferItemPage*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: offeritempage.offertarget
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    offertarget: prismic.ContentRelationshipField<"offerpage">;
    /**
     * Slice Zone field in *OfferItemPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: offeritempage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<OfferitempageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *OfferItemPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: offeritempage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *OfferItemPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: offeritempage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *OfferItemPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: offeritempage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *OfferItemPage → Slice Zone*
 *
 */
type OfferitempageDocumentDataSlicesSlice = ContentSliceSlice | CtaSliceSlice | OfferItemDescriptionSliceSlice;
/**
 * OfferItemPage document from Prismic
 *
 * - **API ID**: `offeritempage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OfferitempageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<OfferitempageDocumentData>,
    "offeritempage",
    Lang
>;
/** Content for OfferPage documents */
interface OfferpageDocumentData {
    /**
     * title field in *OfferPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offerpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * label field in *OfferPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offerpage.label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismic.KeyTextField;
    /**
     * ordinal field in *OfferPage*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: offerpage.ordinal
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    ordinal: prismic.NumberField;
    /**
     * Slice Zone field in *OfferPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: offerpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<OfferpageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *OfferPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: offerpage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *OfferPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: offerpage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *OfferPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: offerpage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *OfferPage → Slice Zone*
 *
 */
type OfferpageDocumentDataSlicesSlice = CtaSliceSlice | ContentSliceSlice | OfferItemsListSliceSlice;
/**
 * OfferPage document from Prismic
 *
 * - **API ID**: `offerpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OfferpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
    Simplify<OfferpageDocumentData>,
    "offerpage",
    Lang
>;
/** Content for PrivacyPage documents */
interface PrivacypageDocumentData {
    /**
     * title field in *PrivacyPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: privacypage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *PrivacyPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: privacypage.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * Slice Zone field in *PrivacyPage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: privacypage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismic.SliceZone<PrivacypageDocumentDataSlicesSlice>;
    /**
     * Meta Description field in *PrivacyPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: privacypage.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismic.RichTextField;
    /**
     * Meta Image field in *PrivacyPage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: privacypage.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismic.ImageField<never>;
    /**
     * Meta Title field in *PrivacyPage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: privacypage.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismic.KeyTextField;
}
/**
 * Slice for *PrivacyPage → Slice Zone*
 *
 */
type PrivacypageDocumentDataSlicesSlice = BlogParagraphSlice;
/**
 * PrivacyPage document from Prismic
 *
 * - **API ID**: `privacypage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacypageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacypageDocumentData>,
    "privacypage",
    Lang
>;
export type AllDocumentTypes =
    | AboutpageDocument
    | BlogpageDocument
    | BlogpostDocument
    | ContactpageDocument
    | ContactpromptDocument
    | FaqindividualquestionDocument
    | FaqpageDocument
    | FooterDocument
    | GlobalnavigationDocument
    | HomepageDocument
    | OfferitempageDocument
    | OfferpageDocument
    | PrivacypageDocument;
/**
 * Primary content in BlogParagraph → Primary
 *
 */
interface BlogParagraphSliceDefaultPrimary {
    /**
     * header field in *BlogParagraph → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_paragraph.primary.header
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    header: prismic.KeyTextField;
    /**
     * content field in *BlogParagraph → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_paragraph.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismic.RichTextField;
}
/**
 * Default variation for BlogParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogParagraphSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<BlogParagraphSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *BlogParagraph*
 *
 */
type BlogParagraphSliceVariation = BlogParagraphSliceDefault;
/**
 * BlogParagraph Shared Slice
 *
 * - **API ID**: `blog_paragraph`
 * - **Description**: `BlogParagraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogParagraphSlice = prismic.SharedSlice<"blog_paragraph", BlogParagraphSliceVariation>;
/**
 * Item in ClientReviewsSlice → Items
 *
 */
export interface ClientReviewsSliceSliceDefaultItem {
    /**
     * image field in *ClientReviewsSlice → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: client_reviews_slice.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * clientName field in *ClientReviewsSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_reviews_slice.items[].clientname
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    clientname: prismic.KeyTextField;
    /**
     * clientCountry field in *ClientReviewsSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_reviews_slice.items[].clientcountry
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    clientcountry: prismic.KeyTextField;
    /**
     * review field in *ClientReviewsSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_reviews_slice.items[].review
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    review: prismic.KeyTextField;
}
/**
 * Default variation for ClientReviewsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientReviewsSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Record<string, never>,
    Simplify<ClientReviewsSliceSliceDefaultItem>
>;
/**
 * Slice variation for *ClientReviewsSlice*
 *
 */
type ClientReviewsSliceSliceVariation = ClientReviewsSliceSliceDefault;
/**
 * ClientReviewsSlice Shared Slice
 *
 * - **API ID**: `client_reviews_slice`
 * - **Description**: `ClientReviewsSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientReviewsSliceSlice = prismic.SharedSlice<"client_reviews_slice", ClientReviewsSliceSliceVariation>;
/**
 * Primary content in ClientTypesSlice → Primary
 *
 */
interface ClientTypesSliceSliceDefaultPrimary {
    /**
     * image field in *ClientTypesSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * title field in *ClientTypesSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
}
/**
 * Item in ClientTypesSlice → Items
 *
 */
export interface ClientTypesSliceSliceDefaultItem {
    /**
     * clientType field in *ClientTypesSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.items[].clienttype
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    clienttype: prismic.KeyTextField;
    /**
     * description field in *ClientTypesSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * linkText field in *ClientTypesSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.items[].linktext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    linktext: prismic.KeyTextField;
    /**
     * link field in *ClientTypesSlice → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: client_types_slice.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismic.LinkField;
}
/**
 * Default variation for ClientTypesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientTypesSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<ClientTypesSliceSliceDefaultPrimary>,
    Simplify<ClientTypesSliceSliceDefaultItem>
>;
/**
 * Slice variation for *ClientTypesSlice*
 *
 */
type ClientTypesSliceSliceVariation = ClientTypesSliceSliceDefault;
/**
 * ClientTypesSlice Shared Slice
 *
 * - **API ID**: `client_types_slice`
 * - **Description**: `ClientTypesSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientTypesSliceSlice = prismic.SharedSlice<"client_types_slice", ClientTypesSliceSliceVariation>;
/**
 * Primary content in CompanyLogos → Primary
 *
 */
interface CompanyLogosSliceDefaultPrimary {
    /**
     * title field in *CompanyLogos → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: company_logos.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
}
/**
 * Item in CompanyLogos → Items
 *
 */
export interface CompanyLogosSliceDefaultItem {
    /**
     * logo field in *CompanyLogos → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_logos.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismic.ImageField<never>;
}
/**
 * Default variation for CompanyLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyLogosSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<CompanyLogosSliceDefaultPrimary>,
    Simplify<CompanyLogosSliceDefaultItem>
>;
/**
 * Slice variation for *CompanyLogos*
 *
 */
type CompanyLogosSliceVariation = CompanyLogosSliceDefault;
/**
 * CompanyLogos Shared Slice
 *
 * - **API ID**: `company_logos`
 * - **Description**: `CompanyLogos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyLogosSlice = prismic.SharedSlice<"company_logos", CompanyLogosSliceVariation>;
/**
 * Primary content in ContentSlice → Primary
 *
 */
interface ContentSliceSliceDefaultPrimary {
    /**
     * displayReturnButton field in *ContentSlice → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: content_slice.primary.displayreturnbutton
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    displayreturnbutton: prismic.BooleanField;
    /**
     * title field in *ContentSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *ContentSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismic.RichTextField;
    /**
     * image field in *ContentSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * contactButtonText field in *ContentSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.contactbuttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contactbuttontext: prismic.KeyTextField;
    /**
     * contactLink field in *ContentSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: content_slice.primary.contactlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contactlink: prismic.LinkField;
}
/**
 * Default variation for ContentSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<ContentSliceSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *ContentSlice*
 *
 */
type ContentSliceSliceVariation = ContentSliceSliceDefault;
/**
 * ContentSlice Shared Slice
 *
 * - **API ID**: `content_slice`
 * - **Description**: `ContentSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceSlice = prismic.SharedSlice<"content_slice", ContentSliceSliceVariation>;
/**
 * Default variation for CtaSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CtaSliceSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *CtaSlice*
 *
 */
type CtaSliceSliceVariation = CtaSliceSliceDefault;
/**
 * CtaSlice Shared Slice
 *
 * - **API ID**: `cta_slice`
 * - **Description**: `CtaSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CtaSliceSlice = prismic.SharedSlice<"cta_slice", CtaSliceSliceVariation>;
/**
 * Primary content in FaqSlice → Primary
 *
 */
interface FaqSliceSliceDefaultPrimary {
    /**
     * mainDescription field in *FaqSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq_slice.primary.maindescription
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    maindescription: prismic.KeyTextField;
}
/**
 * Item in FaqSlice → Items
 *
 */
export interface FaqSliceSliceDefaultItem {
    /**
     * question field in *FaqSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq_slice.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    question: prismic.KeyTextField;
    /**
     * answer field in *FaqSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq_slice.items[].answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    answer: prismic.RichTextField;
    /**
     * detailsLink field in *FaqSlice → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: faq_slice.items[].detailslink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    detailslink: prismic.LinkField;
}
/**
 * Default variation for FaqSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<FaqSliceSliceDefaultPrimary>,
    Simplify<FaqSliceSliceDefaultItem>
>;
/**
 * Slice variation for *FaqSlice*
 *
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;
/**
 * FaqSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: `FaqSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceSlice = prismic.SharedSlice<"faq_slice", FaqSliceSliceVariation>;
/**
 * Primary content in FeaturesSlice → Primary
 *
 */
interface FeaturesSliceSliceDefaultPrimary {
    /**
     * title field in *FeaturesSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
}
/**
 * Item in FeaturesSlice → Items
 *
 */
export interface FeaturesSliceSliceDefaultItem {
    /**
     * icon field in *FeaturesSlice → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features_slice.items[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon: prismic.ImageField<never>;
    /**
     * title field in *FeaturesSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_slice.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *FeaturesSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_slice.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
}
/**
 * Default variation for FeaturesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<FeaturesSliceSliceDefaultPrimary>,
    Simplify<FeaturesSliceSliceDefaultItem>
>;
/**
 * Slice variation for *FeaturesSlice*
 *
 */
type FeaturesSliceSliceVariation = FeaturesSliceSliceDefault;
/**
 * FeaturesSlice Shared Slice
 *
 * - **API ID**: `features_slice`
 * - **Description**: `FeaturesSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSliceSlice = prismic.SharedSlice<"features_slice", FeaturesSliceSliceVariation>;
/**
 * Primary content in MainPitchSlice → Primary
 *
 */
interface MainPitchSliceSliceDefaultPrimary {
    /**
     * Title field in *MainPitchSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismic.RichTextField;
    /**
     * Description field in *MainPitchSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismic.RichTextField;
    /**
     * Image field in *MainPitchSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
    /**
     * Header field in *MainPitchSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.primary.header
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    header: prismic.RichTextField;
}
/**
 * Item in MainPitchSlice → Items
 *
 */
export interface MainPitchSliceSliceDefaultItem {
    /**
     * ContactLink field in *MainPitchSlice → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.items[].contactlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contactlink: prismic.LinkField;
    /**
     * ContactButtonText field in *MainPitchSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_pitch_slice.items[].contactbuttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contactbuttontext: prismic.KeyTextField;
}
/**
 * Default variation for MainPitchSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainPitchSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<MainPitchSliceSliceDefaultPrimary>,
    Simplify<MainPitchSliceSliceDefaultItem>
>;
/**
 * Slice variation for *MainPitchSlice*
 *
 */
type MainPitchSliceSliceVariation = MainPitchSliceSliceDefault;
/**
 * MainPitchSlice Shared Slice
 *
 * - **API ID**: `main_pitch_slice`
 * - **Description**: `MainPitchSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainPitchSliceSlice = prismic.SharedSlice<"main_pitch_slice", MainPitchSliceSliceVariation>;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
    /**
     * Name field in *NavigationItem → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismic.RichTextField;
    /**
     * Link field in *NavigationItem → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismic.LinkField;
}
/**
 * Item in NavigationItem → Items
 *
 */
export interface NavigationItemSliceDefaultItem {
    /**
     * Child Name field in *NavigationItem → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].child_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    child_name: prismic.RichTextField;
    /**
     * Child Link field in *NavigationItem → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].child_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    child_link: prismic.LinkField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<NavigationItemSliceDefaultPrimary>,
    Simplify<NavigationItemSliceDefaultItem>
>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismic.SharedSlice<"navigation_item", NavigationItemSliceVariation>;
/**
 * Item in OfferItemDescriptionSlice → Items
 *
 */
export interface OfferItemDescriptionSliceSliceDefaultItem {
    /**
     * header field in *OfferItemDescriptionSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offer_item_description_slice.items[].header
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    header: prismic.KeyTextField;
    /**
     * mainText field in *OfferItemDescriptionSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offer_item_description_slice.items[].maintext
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    maintext: prismic.RichTextField;
    /**
     * highlightedText field in *OfferItemDescriptionSlice → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: offer_item_description_slice.items[].highlightedtext
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlightedtext: prismic.RichTextField;
}
/**
 * Default variation for OfferItemDescriptionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OfferItemDescriptionSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Record<string, never>,
    Simplify<OfferItemDescriptionSliceSliceDefaultItem>
>;
/**
 * Slice variation for *OfferItemDescriptionSlice*
 *
 */
type OfferItemDescriptionSliceSliceVariation = OfferItemDescriptionSliceSliceDefault;
/**
 * OfferItemDescriptionSlice Shared Slice
 *
 * - **API ID**: `offer_item_description_slice`
 * - **Description**: `OfferItemDescriptionSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OfferItemDescriptionSliceSlice = prismic.SharedSlice<
    "offer_item_description_slice",
    OfferItemDescriptionSliceSliceVariation
>;
/**
 * Primary content in OfferItemsListSlice → Primary
 *
 */
interface OfferItemsListSliceSliceDefaultPrimary {
    /**
     * offerTarget field in *OfferItemsListSlice → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: offer_items_list_slice.primary.offertarget
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    offertarget: prismic.ContentRelationshipField;
}
/**
 * Default variation for OfferItemsListSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OfferItemsListSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<OfferItemsListSliceSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *OfferItemsListSlice*
 *
 */
type OfferItemsListSliceSliceVariation = OfferItemsListSliceSliceDefault;
/**
 * OfferItemsListSlice Shared Slice
 *
 * - **API ID**: `offer_items_list_slice`
 * - **Description**: `OfferItemsListSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OfferItemsListSliceSlice = prismic.SharedSlice<"offer_items_list_slice", OfferItemsListSliceSliceVariation>;
/**
 * Primary content in TeamSlice → Primary
 *
 */
interface TeamSliceSliceDefaultPrimary {
    /**
     * title field in *TeamSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * description field in *TeamSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismic.KeyTextField;
    /**
     * buttonText field in *TeamSlice → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team_slice.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    buttontext: prismic.KeyTextField;
    /**
     * buttonLink field in *TeamSlice → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: team_slice.primary.buttonlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    buttonlink: prismic.LinkField;
    /**
     * image field in *TeamSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: team_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismic.ImageField<never>;
}
/**
 * Default variation for TeamSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSliceSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<TeamSliceSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *TeamSlice*
 *
 */
type TeamSliceSliceVariation = TeamSliceSliceDefault;
/**
 * TeamSlice Shared Slice
 *
 * - **API ID**: `team_slice`
 * - **Description**: `TeamSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSliceSlice = prismic.SharedSlice<"team_slice", TeamSliceSliceVariation>;
/**
 * Primary content in YoutubePlayer → Primary
 *
 */
interface YoutubePlayerSliceDefaultPrimary {
    /**
     * title field in *YoutubePlayer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: youtube_player.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismic.KeyTextField;
    /**
     * videoId field in *YoutubePlayer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: youtube_player.primary.videoid
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    videoid: prismic.KeyTextField;
}
/**
 * Default variation for YoutubePlayer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type YoutubePlayerSliceDefault = prismic.SharedSliceVariation<
    "default",
    Simplify<YoutubePlayerSliceDefaultPrimary>,
    never
>;
/**
 * Slice variation for *YoutubePlayer*
 *
 */
type YoutubePlayerSliceVariation = YoutubePlayerSliceDefault;
/**
 * YoutubePlayer Shared Slice
 *
 * - **API ID**: `youtube_player`
 * - **Description**: `YoutubePlayer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type YoutubePlayerSlice = prismic.SharedSlice<"youtube_player", YoutubePlayerSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type {
            AboutpageDocumentData,
            AboutpageDocumentDataSlicesSlice,
            AboutpageDocument,
            BlogpageDocumentData,
            BlogpageDocumentDataSlicesSlice,
            BlogpageDocument,
            BlogpostDocumentData,
            BlogpostDocumentDataSlicesSlice,
            BlogpostDocument,
            ContactpageDocumentData,
            ContactpageDocumentDataSlicesSlice,
            ContactpageDocument,
            ContactpromptDocumentData,
            ContactpromptDocument,
            FaqindividualquestionDocumentData,
            FaqindividualquestionDocumentDataSlicesSlice,
            FaqindividualquestionDocument,
            FaqpageDocumentData,
            FaqpageDocumentDataSlicesSlice,
            FaqpageDocument,
            FooterDocumentData,
            FooterDocument,
            GlobalnavigationDocumentData,
            GlobalnavigationDocumentDataSlicesSlice,
            GlobalnavigationDocument,
            HomepageDocumentData,
            HomepageDocumentDataSlicesSlice,
            HomepageDocument,
            OfferitempageDocumentData,
            OfferitempageDocumentDataSlicesSlice,
            OfferitempageDocument,
            OfferpageDocumentData,
            OfferpageDocumentDataSlicesSlice,
            OfferpageDocument,
            PrivacypageDocumentData,
            PrivacypageDocumentDataSlicesSlice,
            PrivacypageDocument,
            AllDocumentTypes,
            BlogParagraphSliceDefaultPrimary,
            BlogParagraphSliceDefault,
            BlogParagraphSliceVariation,
            BlogParagraphSlice,
            ClientReviewsSliceSliceDefaultItem,
            ClientReviewsSliceSliceDefault,
            ClientReviewsSliceSliceVariation,
            ClientReviewsSliceSlice,
            ClientTypesSliceSliceDefaultPrimary,
            ClientTypesSliceSliceDefaultItem,
            ClientTypesSliceSliceDefault,
            ClientTypesSliceSliceVariation,
            ClientTypesSliceSlice,
            CompanyLogosSliceDefaultPrimary,
            CompanyLogosSliceDefaultItem,
            CompanyLogosSliceDefault,
            CompanyLogosSliceVariation,
            CompanyLogosSlice,
            ContentSliceSliceDefaultPrimary,
            ContentSliceSliceDefault,
            ContentSliceSliceVariation,
            ContentSliceSlice,
            CtaSliceSliceDefault,
            CtaSliceSliceVariation,
            CtaSliceSlice,
            FaqSliceSliceDefaultPrimary,
            FaqSliceSliceDefaultItem,
            FaqSliceSliceDefault,
            FaqSliceSliceVariation,
            FaqSliceSlice,
            FeaturesSliceSliceDefaultPrimary,
            FeaturesSliceSliceDefaultItem,
            FeaturesSliceSliceDefault,
            FeaturesSliceSliceVariation,
            FeaturesSliceSlice,
            MainPitchSliceSliceDefaultPrimary,
            MainPitchSliceSliceDefaultItem,
            MainPitchSliceSliceDefault,
            MainPitchSliceSliceVariation,
            MainPitchSliceSlice,
            NavigationItemSliceDefaultPrimary,
            NavigationItemSliceDefaultItem,
            NavigationItemSliceDefault,
            NavigationItemSliceVariation,
            NavigationItemSlice,
            OfferItemDescriptionSliceSliceDefaultItem,
            OfferItemDescriptionSliceSliceDefault,
            OfferItemDescriptionSliceSliceVariation,
            OfferItemDescriptionSliceSlice,
            OfferItemsListSliceSliceDefaultPrimary,
            OfferItemsListSliceSliceDefault,
            OfferItemsListSliceSliceVariation,
            OfferItemsListSliceSlice,
            TeamSliceSliceDefaultPrimary,
            TeamSliceSliceDefault,
            TeamSliceSliceVariation,
            TeamSliceSlice,
            YoutubePlayerSliceDefaultPrimary,
            YoutubePlayerSliceDefault,
            YoutubePlayerSliceVariation,
            YoutubePlayerSlice,
        };
    }
}
