// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
    blog_paragraph: dynamic(() => import("./BlogParagraph")),
    client_reviews_slice: dynamic(() => import("./ClientReviewsSlice")),
    client_types_slice: dynamic(() => import("./ClientTypesSlice")),
    content_slice: dynamic(() => import("./ContentSlice")),
    cta_slice: dynamic(() => import("./CtaSlice")),
    faq_slice: dynamic(() => import("./FaqSlice")),
    features_slice: dynamic(() => import("./FeaturesSlice")),
    main_pitch_slice: dynamic(() => import("./MainPitchSlice")),
    navigation_item: dynamic(() => import("./NavigationItem")),
    offer_item_description_slice: dynamic(() => import("./OfferItemDescriptionSlice")),
    offer_items_list_slice: dynamic(() => import("./OfferItemsListSlice")),
    team_slice: dynamic(() => import("./TeamSlice")),
};
